// Autogenerated from Pigeon (v4.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

package pigeon;

import android.util.Log;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import io.flutter.plugin.common.BasicMessageChannel;
import io.flutter.plugin.common.BinaryMessenger;
import io.flutter.plugin.common.MessageCodec;
import io.flutter.plugin.common.StandardMessageCodec;
import java.io.ByteArrayOutputStream;
import java.nio.ByteBuffer;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.HashMap;

/** Generated class from Pigeon. */
@SuppressWarnings({"unused", "unchecked", "CodeBlock2Expr", "RedundantSuppression"})
public class Pigeon {

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class Data {
    private @Nullable String someText;
    public @Nullable String getSomeText() { return someText; }
    public void setSomeText(@Nullable String setterArg) {
      this.someText = setterArg;
    }

    private @Nullable String otherText;
    public @Nullable String getOtherText() { return otherText; }
    public void setOtherText(@Nullable String setterArg) {
      this.otherText = setterArg;
    }

    public static final class Builder {
      private @Nullable String someText;
      public @NonNull Builder setSomeText(@Nullable String setterArg) {
        this.someText = setterArg;
        return this;
      }
      private @Nullable String otherText;
      public @NonNull Builder setOtherText(@Nullable String setterArg) {
        this.otherText = setterArg;
        return this;
      }
      public @NonNull Data build() {
        Data pigeonReturn = new Data();
        pigeonReturn.setSomeText(someText);
        pigeonReturn.setOtherText(otherText);
        return pigeonReturn;
      }
    }
    @NonNull Map<String, Object> toMap() {
      Map<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("someText", someText);
      toMapResult.put("otherText", otherText);
      return toMapResult;
    }
    static @NonNull Data fromMap(@NonNull Map<String, Object> map) {
      Data pigeonResult = new Data();
      Object someText = map.get("someText");
      pigeonResult.setSomeText((String)someText);
      Object otherText = map.get("otherText");
      pigeonResult.setOtherText((String)otherText);
      return pigeonResult;
    }
  }
  private static class DataApiCodec extends StandardMessageCodec {
    public static final DataApiCodec INSTANCE = new DataApiCodec();
    private DataApiCodec() {}
    @Override
    protected Object readValueOfType(byte type, @NonNull ByteBuffer buffer) {
      if (type == (byte) 128) {
        return Data.fromMap((Map<String, Object>) readValue(buffer));
      }
      return super.readValueOfType(type, buffer);
    }
    @Override
    protected void writeValue(@NonNull ByteArrayOutputStream stream, Object value)     {
      if (value instanceof Data) {
        stream.write(128);
        writeValue(stream, ((Data) value).toMap());
      } else 
{
        super.writeValue(stream, value);
      }
    }
  }

  /** Generated interface from Pigeon that represents a handler of messages from Flutter.*/
  public interface DataApi {
    @NonNull List<Data> search(@NonNull String keyword);

    /** The codec used by DataApi. */
    static MessageCodec<Object> getCodec() {
      return DataApiCodec.INSTANCE;
    }

    /** Sets up an instance of `DataApi` to handle messages through the `binaryMessenger`. */
    static void setup(BinaryMessenger binaryMessenger, DataApi api) {
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.DataApi.search", getCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              ArrayList<Object> args = (ArrayList<Object>)message;
              assert args != null;
              String keywordArg = (String)args.get(0);
              if (keywordArg == null) {
                throw new NullPointerException("keywordArg unexpectedly null.");
              }
              List<Data> output = api.search(keywordArg);
              wrapped.put("result", output);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
    }
  }
  private static Map<String, Object> wrapError(Throwable exception) {
    Map<String, Object> errorMap = new HashMap<>();
    errorMap.put("message", exception.toString());
    errorMap.put("code", exception.getClass().getSimpleName());
    errorMap.put("details", "Cause: " + exception.getCause() + ", Stacktrace: " + Log.getStackTraceString(exception));
    return errorMap;
  }
}
